server:
  port: ${PORT:8082}
spring:
  application:
    name: orders-communications

  ## RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:Admin123*}
    virtual-host: ${RABBITMQ_VHOST:/}

  # Configuración de correo electrónico
  mail:
    host: smtp.gmail.com
    port: 587
    username: devner.99@gmail.com
    password: qgddxvsappgjstra
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

## Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}

## RabbitMQ Event Configuration
rabbitmq:
  queue:
    mails:
      order-created: mails.order.created
  exchange:
    orders: pedidos.creados
  routing:
    key:
      order:
        created: order.created

# Configuración de notificaciones por correo
email:
  notification:
    to: ${NOTIFICATION_EMAIL:bryan.cruz386.bsca@gmail.com} # Cambia esto por el correo del destinatario
    from: ${FROM_EMAIL:UNIR Relatos de Papel Ebook <bryan.cruz386.bsca@gmail.com>}

# Configuración de logging
logging:
  level:
    com.orders.relatosdepapel.communications: DEBUG
    org.springframework.amqp: INFO
    org.springframework.mail: DEBUG

# Configuración de Gemini API
gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
